[package]
name = "steak"
version = "0.1.0"
authors = ["larry <gm@larry.engineer>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/stakehaus1/steak-contracts"

[dependencies]
cosmwasm-std = "0.16"
cw20 = "0.9"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = "2.2"
